version: '3'  

services:

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud_db
    restart: always

  redis:
    image: redis:alpine
    restart: always
            
                
  app:
    image: nextcloud:apache
    hostname: ${NEXTCLOUD_HOST}
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /docker/nextcloud/php.ini:/usr/local/etc/php/php.ini
      - /etc/localtime:/etc/localtime:ro

    environment:
      # for nginx proxy and letsencrypt
      - VIRTUAL_HOST=${NEXTCLOUD_HOST}
      - LETSENCRYPT_HOST=${NEXTCLOUD_HOST}

      # Nextcloud env vars required for autoconfig
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_HOST} ${NEXTCLOUD_TRUSTED_DOMAINS}
      - NEXTCLOUD_UPDATE=1
      - REDIS_HOST=redis
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud_db  
      - OVERWRITEPROTOCOL=https

    restart: always
    #command: -u www-data php occ db:convert-filecache-bigint --no-interaction

    cron:
      image: nextcloud:apache
      restart: always
      volumes:
        - nextcloud:/var/www/html
      entrypoint: /cron.sh
      depends_on:
        - db
        - redis
  

  
      
volumes:
  nextcloud:
  db:
         
      
networks:
    default:
        external:
            name: nginx-proxy
  
